# Generated by Django 4.2.4 on 2023-12-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0004_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='location',
        ),
    ]
