# Generated by Django 4.2.4 on 2023-12-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0005_remove_match_date_remove_match_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.FloatField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplauction.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplauction.match')),
            ],
        ),
        migrations.CreateModel(
            name='BattingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplauction.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplauction.match')),
            ],
        ),
    ]
