# Generated by Django 4.2.4 on 2023-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0006_bowlingscorecard_battingscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='overs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
    ]
