# Generated by Django 4.1.13 on 2024-02-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0007_match_overs_match_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlingscorecard',
            name='bowler',
        ),
        migrations.RemoveField(
            model_name='bowlingscorecard',
            name='match',
        ),
        migrations.DeleteModel(
            name='BattingScorecard',
        ),
        migrations.DeleteModel(
            name='BowlingScorecard',
        ),
    ]
