# Generated by Django 4.1.13 on 2024-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0008_remove_bowlingscorecard_bowler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='international_team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets_taken',
            field=models.IntegerField(default=0),
        ),
    ]
