# Generated by Django 4.1.13 on 2024-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0009_player_batting_style_player_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(choices=[('Right-Handed-Bat', 'Right-Handed-Bat'), ('Left-Handed-Bat', 'Left-Handed-Bat')], max_length=100),
        ),
    ]
