# Generated by Django 4.1.13 on 2024-02-27 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0010_alter_player_batting_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('venue_description', models.TextField()),
                ('venue_picture', models.ImageField(upload_to='venue_pictures/')),
            ],
        ),
    ]
