# Generated by Django 4.1.13 on 2024-02-27 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0011_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
