# Generated by Django 4.1.13 on 2024-03-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0014_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
