# Generated by Django 4.1.13 on 2024-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0017_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
